### PR TITLE
Add reset command

### PR DESCRIPTION
**Pull request by bridadan**
I should warn that I'm still a beginner Rustacean, so please feel free to suggest any and all changes!

### CODE REVIEW

**Review by Frank-Buss — COMMENTED** [review]
Thanks, I'll test it tomorrow. Looks good, but one minor thing: Why did you change the signature of `new_req`? If `id` has the type `NmpIdImage` (and the calling function `encode_request`), then it is less likely that an invalid `u8` is passed. I guess in parts my fault, because IMHO it should be typed in `struct NmpHdr` as well (same as `group`), and only converted to `u8` for the serialization.

**Comment by bridadan** [comment]
Hey there, thanks for taking a look!

If I don't change the function signature then I get the following error when building:

```
$ cargo build --release
   Compiling mcumgr-client v0.0.3 (/home/bridadan/dev/mcumgr-client)
error[E0308]: mismatched types
  --> src/default.rs:28:9
   |
24 |     let (data, request_header) = encode_request(
   |                                  -------------- arguments to this function are incorrect
...
28 |         NmpIdDef::Reset,
   |         ^^^^^^^^^^^^^^^ expected `NmpIdImage`, found `NmpIdDef`
   |
note: function defined here
  --> src/transfer.rs:55:8
   |
55 | pub fn encode_request(
   |        ^^^^^^^^^^^^^^
...
59 |     id: NmpIdImage,
   |     --------------

For more information about this error, try `rustc --explain E0308`.
error: could not compile `mcumgr-client` (bin "mcumgr-client") due to 1 previous error
```

Since the Reset ID is not a `NmpIdImage` but an `NmpIdDef` instead, I made it the more generic `u8` type. Perhaps there's a cleaner way to do this so I don't have to have add all of those `x as u8` casts? Very open to suggestions here!

**Comment by Frank-Buss** [comment]
You could define a common trait for it, which is implemented for the 2 enums. This would at least allow to make it typesafe for the function calls. I'm not that much of a Rust expert, couldn't get it better in the NmpHdr structure because of the deserialize function (not clear which trait implementation to choose), but I think it is fine to use u8 for the struct member itself, no need to make it unnecessary complicated. Changes:

```
diff --git a/src/default.rs b/src/default.rs
index 285ce26..b558fca 100644
--- a/src/default.rs
+++ b/src/default.rs
@@ -25,7 +25,7 @@ pub fn reset(cli: &Cli) -> Result<(), Error> {
         cli.linelength,
         NmpOp::Write,
         NmpGroup::Default,
-        NmpIdDef::Reset as u8,
+        NmpIdDef::Reset,
         &body,
         next_seq_id(),
     )?;
diff --git a/src/image.rs b/src/image.rs
index 60d6eda..f69f90e 100644
--- a/src/image.rs
+++ b/src/image.rs
@@ -33,7 +33,7 @@ pub fn list(cli: &Cli) -> Result<(), Error> {
         cli.linelength,
         NmpOp::Read,
         NmpGroup::Image,
-        NmpIdImage::State as u8,
+        NmpIdImage::State,
         &body,
         next_seq_id(),
     )?;
@@ -131,7 +131,7 @@ pub fn upload(cli: &Cli, filename: &PathBuf) -> Result<(), Error> {
                 cli.linelength,
                 NmpOp::Write,
                 NmpGroup::Image,
-                NmpIdImage::Upload as u8,
+                NmpIdImage::Upload,
                 &body,
                 seq_id,
             )?;
diff --git a/src/nmp_hdr.rs b/src/nmp_hdr.rs
index 9c9cd19..a502902 100644
--- a/src/nmp_hdr.rs
+++ b/src/nmp_hdr.rs
@@ -44,6 +44,10 @@ pub enum NmpGroup {
     PerUser = 64,
 }
 
+pub trait NmpId {
+    fn to_u8(&self) -> u8;
+}
+
 #[repr(u8)]
 #[derive(Debug, Copy, Clone)]
 pub enum NmpIdDef {
@@ -55,6 +59,12 @@ pub enum NmpIdDef {
     Reset = 5,
 }
 
+impl NmpId for NmpIdDef {
+    fn to_u8(&self) -> u8 {
+        *self as u8
+    }
+}
+
 #[repr(u8)]
 #[derive(Debug, Copy, Clone)]
 pub enum NmpIdImage {
@@ -65,6 +75,12 @@ pub enum NmpIdImage {
     Erase = 5,
 }
 
+impl NmpId for NmpIdImage {
+    fn to_u8(&self) -> u8 {
+        *self as u8
+    }
+}
+
 #[repr(u8)]
 #[derive(Debug, Copy, Clone)]
 pub enum NmpIdStat {
@@ -125,14 +141,14 @@ pub struct NmpHdr {
 }
 
 impl NmpHdr {
-    pub fn new_req(op: NmpOp, group: NmpGroup, id: u8) -> NmpHdr {
+    pub fn new_req(op: NmpOp, group: NmpGroup, id: impl NmpId) -> NmpHdr {
         NmpHdr {
             op,
             flags: 0,
             len: 0,
             group,
             seq: 0,
-            id: id,
+            id: id.to_u8(),
         }
     }
 
diff --git a/src/test_serial_port.rs b/src/test_serial_port.rs
index 6cd748b..63bf000 100644
--- a/src/test_serial_port.rs
+++ b/src/test_serial_port.rs
@@ -85,7 +85,7 @@ impl Write for TestSerialPort {
                     100,
                     NmpOp::ReadRsp,
                     NmpGroup::Image,
-                    NmpIdImage::State as u8,
+                    NmpIdImage::State,
                     &body,
                     request_header.seq,
                 )
@@ -115,7 +115,7 @@ impl Write for TestSerialPort {
                     4096,
                     NmpOp::WriteRsp,
                     NmpGroup::Image,
-                    NmpIdImage::State as u8,
+                    NmpIdImage::State,
                     &cbor_body,
                     request_header.seq,
                 )
diff --git a/src/transfer.rs b/src/transfer.rs
index f4c13c0..f72ea33 100644
--- a/src/transfer.rs
+++ b/src/transfer.rs
@@ -56,7 +56,7 @@ pub fn encode_request(
     linelength: usize,
     op: NmpOp,
     group: NmpGroup,
-    id: u8,
+    id: impl NmpId,
     body: &Vec<u8>,
     seq_id: u8,
 ) -> Result<(Vec<u8>, NmpHdr), Error> {
```

**Comment by bridadan** [comment]
Agreed, I would prefer to have the type safety as well. Your solution is much more elegant, thanks for the suggestion! I've pushed the changes.

**Comment by Frank-Buss** [comment]
Thanks, I tested it and it work.

**Comment by bridadan** [comment]
Thanks again for the quick review! Do you have a release schedule? No rush or anything, happy to keep local builds going as needed, but more than happy to drop local builds for upstream :slightly_smiling_face:

**Comment by Frank-Buss** [comment]
There is no schedule, but I created a new release.

**Comment by bridadan** [comment]
Oh great, thanks!

**Pull request merged**
